# Generated by Django 4.0.6 on 2022-07-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_url_full_url_alter_url_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='uuid',
            new_name='short_url',
        ),
    ]
